services:
  site-pdv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site_pdv_teltech
    restart: unless-stopped
    ports:
      - "3529:3529"
    environment:
      - NODE_ENV=production
      - PORT=3529
      - HOST=0.0.0.0
